# Generated by Django 5.2.7 on 2025-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('medicacion', models.BooleanField(default=False)),
                ('medicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis_diaria', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
